collections:
- name: arista.eos
  source: https://galaxy.ansible.com
- name: cisco.ios
  source: https://galaxy.ansible.com
- name: cisco.nxos
  source: https://galaxy.ansible.com
- name: vyos.vyos
  source: https://galaxy.ansible.com
- name: ansible.utils
  source: https://galaxy.ansible.com
